### ISSUE TITLE
auth: save(namespaces) method results in invalid left-hand assignment

### ISSUE THREAD

**Issue by nakajimayoshi** [Navigraph/navigraph-js-sdk#66]
### Description

Using the code sandbox example in a local environment, I expected the result to work exactly the same, but the left hand assignment results in the program not running.

### Steps to reproduce

Setup a new tauri or vite project and copy all the files from https://codesandbox.io/s/navigraph-sdk-demo-1pfk48

### Navigraph SDK Version(s)

auth@2.4.0

### environment

WebView2 (Tauri)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I have an .env file in my local setup with a navigraph client id and secret, but no debug value. 

The bug was resolved by commenting out any method in the node_modules/@navigraph/auth/dist/index.cjs.js and index.esm.js with the following signature:

```ts
function save(namespaces){}
```

**Comment by SkySails** [comment]
Do you know if this started happening recently, or is this your first time using the SDK?

On initial inspection, this sounds more like an issue with your own code or build tools, for several reasons.

1. The code you are referencing is from an upstream dependency: [debug](https://www.npmjs.com/package/debug). You can the referenced signature in three places, [here](https://github.com/debug-js/debug/blob/f66cb2d9f729e1a592e72d3698e3b75329d75a25/src/browser.js#L191-L208), [here](https://github.com/debug-js/debug/blob/f66cb2d9f729e1a592e72d3698e3b75329d75a25/src/common.js#L155-L187) and [here](https://github.com/debug-js/debug/blob/f66cb2d9f729e1a592e72d3698e3b75329d75a25/src/node.js#L197-L211). None of these instances contain an invalid left-hand assignment (which is fortunate, since the library has 231 million downloads every week).
2. Our code is compiled down to ES5 levels of compatibility. This should work in modern build tools like Vite, but if you have a custom configuration then there might be implications.
3. We are running this SDK in production in projects powered by Vite and Webpack without any issues.

Could you perhaps provide more information, such as a reproducible example? A public GitHub repository for example.

> **Warning**
> The use of our SDK and/or APIs in a desktop application is _not permitted_. I am assuming that you are just trying things out. For more information, please see our documentation, which it seems you have already found:
https://developers.navigraph.com/docs/general/restrictions#no-charts-in-desktop-apps

**Comment by nakajimayoshi** [comment]
@SkySails First time using the SDK. 

MRE: 
https://github.com/nakajimayoshi/example-navigraph

[Instructions for setting up acev3 environment](https://github.com/synapticsim/ace-v3/tree/master)

As for the warning, **Ace is a developer tool not a production desktop application**. If this is an issue, I can move development over to a browser. The only difference between ACE and a browser is that ACE works with bundles and natively supports Coherent GT debugging, whereas the browser doesn't. There are no plans for desktop app.
